import { localization } from "../localizationManager";

export var frenchStrings = {
    groupButton: "Grouper",
    ungroupButton: "Dissocier",
    selectButton: "Sélectionner",
    hideColumn: "Masquer colonne",
    showColumn: "Afficher colonne",
    makePrivateColumn: "Rendre la colonne privé",
    makePublicColumn: "Rendre la colonne public",
    moveToDetail: "Déplacer vers détails",
    showAsColumn: "Afficher en colonne",
    filterPlaceholder: "Rechercher...",
    removeRows: "Supprimer colonne",
    showLabel: "Afficher",
    entriesLabel: "entrées",
    visualizer_text: "Textes en table",
    visualizer_wordcloud: "Nuages de mots",
    visualizer_histogram: "Histogramme",
    visualizer_number: "Moyenne",
    visualizer_choices: "Table",
    visualizer_selectBase: "Chart",
    chartType_bar: "Barres",
    chartType_vbar: "Vertical Bar",
    chartType_stackedbar: "Barres empilées",
    chartType_doughnut: "Anneau",
    chartType_pie: "Camembert",
    chartType_scatter: "Nuages de points",
    chartType_gauge: "Gauge",
    chartType_bullet: "Bulles",
    hideButton: "Masquer",
    makePrivateButton: "Rendre privé",
    makePublicButton: "Rendre publique",
    showButton: "Afficher",
    filter: "Filtre",
    resetFilter: "Rafraichir Filtres",
    changeLocale: "Changer la langue",
    en: "English",
    fr: "Français",
    ru: "Русский",
    de: "Deutsch",
    clearButton: "Rafraichir",
    addElement: "Choisir la question à afficher...",
    defaultOrder: "Ordre par défaut",
    ascOrder: "Ascendant",
    descOrder: "Descendant",
    showMinorColumns: "Afficher les colonnes mineures",
    otherCommentTitle: "Autre élément et commentaires",
    showPercentages: "Show percentages",
    hidePercentages: "Hide percentages",
    pdfDownloadCaption: "PDF",
    xlsxDownloadCaption: "Excel",
    csvDownloadCaption: "CSV",
    saveDiagramAsPNG: "Sauver en png",
    hideEmptyAnswers: "Cacher les réponses vides",
    showEmptyAnswers: "Afficher les réponses vides",
    "topNValueText-1": "Toutes les réponses",
    "topNValueText5": "Top 5 des réponses",
    "topNValueText10": "Top 10 des réponses",
    "topNValueText20": "Top 20 des réponses",
    hideMissingAnswers: "Cacher les réponses manquantes",
    showMissingAnswers: "Afficher les réponses manquantes",
    missingAnswersLabel: "Réponses manquantes",
    noVisualizerForQuestion: "Ce type de question n'est pas encore visualisé",
    noResults: "Il n'y a pas encore de résultats",
    showPerValues: "Par valeur",
    showPerColumns: "Par colonne",
    answer: "Réponse",
    correctAnswer: "Réponse correcte: ",
    percent: "Pourcentage",
    responses: "Réponses"
};

localization.locales["fr"] = frenchStrings;
localization.localeNames["fr"] = "French";
